@startuml
title Monitor de Coagulação: Tratamento de Falhas e Alarmes

participant "Monitor de Coagulação:" as MC
participant Sensores as S
participant "Bombas" as B
participant Gateway as GW

GW -> S: Lê sensores
S --> GW: Retorna valores

GW -> MC: Comando de Dose(Turbidez, pH, ...)

alt Sensor OK
    MC -> B: Ajusta bomba
    B --> MC: Status

    alt Falha na bomba
        MC -> MC: Gera alarme de atuador
        MC --> GW: Notifica falha (Bomba não responde)
    else Bombas OK
        MC -> MC: Continua operação
        MC --> GW: Notificar sucesso (Dosagem atual)
    end
else Sensor Error
    MC --> GW: Notifica erro (Parâmetros fora do padrão)
end

@enduml