@startuml
title Monitor de Coagulação:: Envio de Dados para AWS

participant "Monitor de Coagulação:" as MC
participant Gateway as GW
participant AWS as AWS
participant Sensores as S

loop Ciclo de envio
    GW -> S: Leitura dos Sensores
    S --> GW: Retorna leituras

    GW -> MC: Dose (Turbidez, pH, ...)
    MC --> GW: Dosagem Atual

    GW -> GW: Monta pacote de envio

    GW -> AWS: Envia dados
    alt Sucesso
        AWS --> GW: Confirma recebimento
    else Falha de comunicação
        GW -> GW: Armazena para retry
    end
end

@enduml