@startuml
title Monitor de Coagulação:: Controle Automático

participant Gateway as GW
participant "Monitor de Coagulação:" as MC
participant Sensores as S
participant "Bombas \n (Alcalinizante/Coagulante)" as B
participant "Sensores de Vazão \n (Alcalinizante/Coagulante)" as V

loop Ciclo contínuo de controle

    GW -> MC: Dose  (pH, turbidez, etc.)


    MC -> MC: Calcula a dosagem necessária

    MC -> B: Ajusta a vazão das bombas
    B --> MC: Confirma ajuste

    MC -> V: Lê sensores de vazão
    V --> MC: Retorna vazão real

    MC -> MC: Compara vazão desejada x vazão real

    alt Vazão dentro do esperado
        MC -> MC: Mantém configuração
    else Vazão fora do esperado
        MC -> B: Reajusta a vazão
    end

    MC --> GW: Retorna a Dosagem Atual
end

@enduml