@startuml
title Monitor de Coagulação:: Configuração de Sensores

actor Fabricante as F
participant "Monitor de Coagulação:" as MC

F -> MC: Configuração Sensores (parâmetro)

alt Adicionar sensor
    MC -> MC: Registra novo sensor
else Alterar sensor
    MC -> MC: Atualiza parâmetros
else Remover sensor
    MC -> MC: Remove sensor
end

MC -> MC: Salva configuração

MC -> F: Confirma operação

@enduml